app:
  baseUrl: ${APP_URL}
backend:
  baseUrl: ${APP_URL}
  cors:
    origin:
      - ${APP_URL}
    credentials: true
    methods: [GET, POST, PUT, DELETE, OPTIONS]
    allowedHeaders: ['Authorization', 'Content-Type']
  database:
    client: pg
    connection: ${POSTGRES_CONNECTION_STRING}
auth:
  environment: production
  providers:
    github:
      production:
        clientId: Iv23liZxhuxGanrXZu7R
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
