app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
organization:
  name: Vercevo
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", "http:", "https:"]
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID_DEV}
        clientSecret: ${GITHUB_CLIENT_SECRET_DEV}
        callbackUrl: http://localhost:7007/api/auth/github/handler/frame
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
catalog:
  providers:
    github:
      providerId:
        organization: 'vercevo'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '.*'
    githubOrg:
      - id: development
        githubUrl: https://github.com
        orgs: ['vercevo']
        schedule:
          initialDelay: {seconds: 5}
          frequency: {hours: 1}
          timeout: {minutes: 50}
        catalogPath: '/catalog-info.yaml'
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  useUrlReadersSearch: true
permission:
  enabled: true
logger:
  level: debug
