auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        callbackUrl: https://backstage.bergtobias.com/api/auth/github/handler/frame
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
kubernetes:
  serviceLocatorMethod:
    type: singleTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: https://192.168.10.219:6443
          name: homelab
          authProvider: serviceAccount
          skipTLSVerify: false
          serviceAccountToken: ${K8_SERVICE_TOKEN}
          caData: ${K8_CA_DATA}
          namespace:
            - '*'
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
