app:
  title: Scaffolded Backstage App
  baseUrl: ${APP_URL}
organization:
  name: Vercevo
backend:
  baseUrl: ${BACKEND_BASEURL}
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", "http:", "https:"]
  cors:
    origin: ${APP_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      connectionString: ${POSTGRES_CONNECTION_STRING}
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        callbackUrl: ${BACKEND_BASEURL}/api/auth/github/handler/frame
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
catalog:
  providers:
    github:
      providerId:
        organization: 'vercevo'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '.*'
    githubOrg:
      - id: production
        githubUrl: https://github.com
        orgs: ['vercevo']
        schedule:
          initialDelay: {seconds: 5}
          frequency: {hours: 1}
          timeout: {minutes: 50}
        catalogPath: '/catalog-info.yaml'
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  useUrlReadersSearch: true
permission:
  enabled: true
kubernetes:
  serviceLocatorMethod:
    type: singleTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: ${K8_URL}
          name: homelab
          authProvider: serviceAccount
          skipTLSVerify: false
          serviceAccountToken: ${K8_SERVICE_TOKEN}
          caData: ${K8_CA_DATA}
          namespace:
            - '*'
