app:
  baseUrl: https://backstage.bergtobias.com
backend:
  baseUrl: https://backstage.bergtobias.com
  cors:
    origin: https://backstage.bergtobias.com
    credentials: true
    methods: [GET, POST, PUT, DELETE, OPTIONS]
    allowedHeaders: ['Authorization', 'Content-Type']
  database:
    client: pg
    connection: ${POSTGRES_CONNECTION_STRING}
