apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  links:
    - url: https://backstage.bergtobias.com
spec:
  type: website
  owner: group:default/eggmans
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: platform-systems
spec:
  type: url
  target: https://github.com/vercevo/platform-infra/blob/main/systems
