name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    outputs:
      short_sha: ${{ steps.get-sha.outputs.short_sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Show runner architecture
        run: uname -m
        # Expect output: arm64 on macos-latest ARM runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Inspect buildx builder
        run: docker buildx inspect --bootstrap
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: get-sha
        name: Get short commit SHA
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and push Docker image with cache
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            -t ghcr.io/${{ github.repository_owner }}/backstage:${{ steps.get-sha.outputs.short_sha }} \
            -t ghcr.io/${{ github.repository_owner }}/backstage:latest \
            --push .
