name: Build and Push ARM64 Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: [self-hosted, linux, arm64]
    permissions:
      packages: write
      contents: read
    outputs:
      short_sha: ${{ steps.get-sha.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: get-sha
        name: Get short commit SHA
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image (ARM64)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ghcr.io/${{ github.repository_owner }}/backstage:${{ steps.get-sha.outputs.short_sha }} \
            -t ghcr.io/${{ github.repository_owner }}/backstage:latest \
            --push .
