name: Build and Push Docker Image (No Buildx)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: macos-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get short commit SHA
        id: get-sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker image (no buildx, local arch only)
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/backstage:${{ steps.get-sha.outputs.short_sha }} \
            -t ghcr.io/${{ github.repository_owner }}/backstage:latest \
            .
          docker push ghcr.io/${{ github.repository_owner }}/backstage:${{ steps.get-sha.outputs.short_sha }}
          docker push ghcr.io/${{ github.repository_owner }}/backstage:latest
