name: Build and Update Manifests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      short_sha: ${{ steps.get-sha.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: get-sha
        name: Get short commit SHA
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and Push Docker image
        run: |-
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            -t ghcr.io/${{ github.repository_owner }}/eggman:${{ steps.get-sha.outputs.short_sha }} \
            --push .
